# Generated by Django 5.1.7 on 2025-06-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_telegram_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_login',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
